# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 219947ed9792a581250f059a67d8ecadbaa52bc8a03486390430d9d7824a20714ff7125948fb27c4b8980e36127e810f6d1829d08d4433246591b76feed31e58

test:
  secret_key_base: 3f58745f00f3e8d6179e77f1da24e8aaa7cd325ea12e2409a2bce123687503d90403c31663a641da885d009b7a77eaf05db1a05dc27b786d6db3c4ac4ea96892

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
